export const industries = [
    { value: 'accounting', label: 'Accounting' },
    { value: 'advertising', label: 'Advertising' },
    { value: 'aerospace', label: 'Aerospace' },
    { value: 'agriculture', label: 'Agriculture' },
    { value: 'airlines', label: 'Airlines' },
    { value: 'alternative energy', label: 'Alternative Energy' },
    { value: 'architecture', label: 'Architecture' },
    { value: 'automotive', label: 'Automotive' },
    { value: 'banking', label: 'Banking' },
    { value: 'biotechnology', label: 'Biotechnology' },
    { value: 'chemical', label: 'Chemical' },
    { value: 'construction', label: 'Construction' },
    { value: 'consulting', label: 'Consulting' },
    { value: 'consumer goods', label: 'Consumer Goods' },
    { value: 'cosmetics', label: 'Cosmetics' },
    { value: 'defense', label: 'Defense' },
    { value: 'education', label: 'Education' },
    { value: 'electronics', label: 'Electronics' },
    { value: 'energy', label: 'Energy' },
    { value: 'entertainment', label: 'Entertainment' },
    { value: 'environmental', label: 'Environmental' },
    { value: 'fashion', label: 'Fashion' },
    { value: 'finance', label: 'Finance' },
    { value: 'food', label: 'Food' },
    { value: 'gaming', label: 'Gaming' },
    { value: 'government', label: 'Government' },
    { value: 'healthcare', label: 'Healthcare' },
    { value: 'hospitality', label: 'Hospitality' },
    { value: 'human resources', label: 'Human Resources' },
    { value: 'information technology', label: 'Information Technology' },
    { value: 'insurance', label: 'Insurance' },
    { value: 'internet', label: 'Internet' },
    { value: 'investment', label: 'Investment' },
    { value: 'legal', label: 'Legal' },
    { value: 'logistics', label: 'Logistics' },
    { value: 'manufacturing', label: 'Manufacturing' },
    { value: 'market research', label: 'Market Research' },
    { value: 'media', label: 'Media' },
    { value: 'mining', label: 'Mining' },
    { value: 'music', label: 'Music' },
    { value: 'non-profit', label: 'Non-Profit' },
    { value: 'oil and gas', label: 'Oil and Gas' },
    { value: 'pharmaceutical', label: 'Pharmaceutical' },
    { value: 'public relations', label: 'Public Relations' },
    { value: 'publishing', label: 'Publishing' },
    { value: 'real estate', label: 'Real Estate' },
    { value: 'recruitment', label: 'Recruitment' },
    { value: 'retail', label: 'Retail' },
    { value: 'sales', label: 'Sales' },
    { value: 'social media', label: 'Social Media' },
    { value: 'sports', label: 'Sports' },
    { value: 'technology', label: 'Technology' },
    { value: 'telecommunications', label: 'Telecommunications' },
    { value: 'tourism', label: 'Tourism' },
    { value: 'transportation', label: 'Transportation' },
    { value: 'travel', label: 'Travel' },
    { value: 'utilities', label: 'Utilities' },
    { value: 'venture capital', label: 'Venture Capital' },
    { value: 'web development', label: 'Web Development' },
    { value: 'waste management', label: 'Waste Management' },
]
export const genders = [
    { value: 'man', label: 'Man' },
    { value: 'woman', label: 'Woman' },
    { value: 'other', label: 'Other' },
    { value: 'no-response', label: 'Prefer not to respond' }
]